In [1]:
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sklearn

In [2]:
df = pd.read_csv(r"C:\Users\Niranjan\Desktop\Data Science\datasets\Supervised learning potpourri\creditcardfraud.csv")
df.head(5)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [3]:
df.isnull().sum().sum()

0

In [4]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
# load data
array = df.values
print(array)
type(array)

[[ 0.00000000e+00 -1.35980713e+00 -7.27811733e-02 ... -2.10530535e-02
   1.49620000e+02  0.00000000e+00]
 [ 0.00000000e+00  1.19185711e+00  2.66150712e-01 ...  1.47241692e-02
   2.69000000e+00  0.00000000e+00]
 [ 1.00000000e+00 -1.35835406e+00 -1.34016307e+00 ... -5.97518406e-02
   3.78660000e+02  0.00000000e+00]
 ...
 [ 1.72788000e+05  1.91956501e+00 -3.01253846e-01 ... -2.65608286e-02
   6.78800000e+01  0.00000000e+00]
 [ 1.72788000e+05 -2.40440050e-01  5.30482513e-01 ...  1.04532821e-01
   1.00000000e+01  0.00000000e+00]
 [ 1.72792000e+05 -5.33412522e-01 -1.89733337e-01 ...  1.36489143e-02
   2.17000000e+02  0.00000000e+00]]


numpy.ndarray

In [5]:
X = array[:,0:30]
Y = array[:,30]
# feature extraction
test = SelectKBest(score_func=f_classif, k=10)
fit = test.fit(X, Y)
# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])

[4.325e+01 2.956e+03 2.393e+03 1.101e+04 5.164e+03 2.592e+03 5.435e+02
 1.035e+04 1.125e+02 2.747e+03 1.406e+04 6.999e+03 2.075e+04 5.948e+00
 2.870e+04 5.080e+00 1.144e+04 3.398e+04 3.584e+03 3.450e+02 1.150e+02
 4.659e+02 1.847e-01 2.053e+00 1.485e+01 3.116e+00 5.654e+00 8.805e+01
 2.590e+01 9.033e+00]
[[ 2.536  1.378  0.24   0.091 -0.552 -0.618 -0.311 -0.47   0.208  0.026]
 [ 0.166  0.448 -0.079 -0.167  1.613  1.065 -0.144  0.464 -0.115 -0.183]
 [ 1.773  0.38   0.791  0.208  0.625  0.066 -0.166 -2.89   1.11  -0.121]
 [ 1.793 -0.863  0.238 -0.055 -0.226  0.178 -0.288 -1.06  -0.684  1.966]
 [ 1.549  0.403  0.593  0.753 -0.823  0.538 -1.12  -0.451 -0.237 -0.038]]


In [6]:
features

array([[ 2.536,  1.378,  0.24 , ..., -0.47 ,  0.208,  0.026],
       [ 0.166,  0.448, -0.079, ...,  0.464, -0.115, -0.183],
       [ 1.773,  0.38 ,  0.791, ..., -2.89 ,  1.11 , -0.121],
       ...,
       [-3.25 , -0.558, -0.297, ...,  0.141,  0.314,  0.396],
       [ 0.703,  0.69 , -0.686, ..., -0.609,  0.51 ,  1.114],
       [ 0.703, -0.506,  1.577, ..., -0.303, -0.66 ,  0.167]])

In [7]:
cols = fit.get_support(indices=True)
cols = np.append(cols, 30)
cols

array([ 3,  4,  7, 10, 11, 12, 14, 16, 17, 18, 30], dtype=int64)

In [8]:
df_new =  df.columns[cols]


In [9]:
type(df_new)

pandas.core.indexes.base.Index

In [10]:
df_selectedfeatures = df[df_new]
df_selectedfeatures.head(5)

V3        V4        V7       V10       V11       V12       V14  \
0  2.536347  1.378155  0.239599  0.090794 -0.551600 -0.617801 -0.311169   
1  0.166480  0.448154 -0.078803 -0.166974  1.612727  1.065235 -0.143772   
2  1.773209  0.379780  0.791461  0.207643  0.624501  0.066084 -0.165946   
3  1.792993 -0.863291  0.237609 -0.054952 -0.226487  0.178228 -0.287924   
4  1.548718  0.403034  0.592941  0.753074 -0.822843  0.538196 -1.119670   

        V16       V17       V18  Class  
0 -0.470401  0.207971  0.025791      0  
1  0.463917 -0.114805 -0.183361      0  
2 -2.890083  1.109969 -0.121359      0  
3 -1.059647 -0.684093  1.965775      0  
4 -0.451449 -0.237033 -0.038195      0

In [11]:
from sklearn.naive_bayes import BernoulliNB

# Instantiate our model and store it in a new variable.
bnb = BernoulliNB()

# Fit our model to the data.
X = df.loc[:, ~df.columns.isin(['Class'])]
Y = df['Class']
bnb.fit(X, Y)

# Classify, storing the result in a new variable.
y_pred = bnb.predict(X)

In [12]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y, y_pred)

array([[284246,     69],
       [   174,    318]], dtype=int64)

In [13]:
from sklearn.model_selection import train_test_split
# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=20)
print('With 30% Holdout for Naive Bayes: ' + str(bnb.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on the entire dataset for Naive Bayes: ' + str(bnb.fit(X, Y).score(X, Y)))
confusion_matrix(y_test, bnb.predict(X_test))

With 30% Holdout for Naive Bayes: 0.9992275552122467
Testing on the entire dataset for Naive Bayes: 0.9991467906336572


array([[85288,    19],
       [   47,    89]], dtype=int64)

In [14]:
from sklearn.model_selection import cross_val_score
print("Cross validation for Naive Bayes: ",cross_val_score(bnb, X, Y, cv=10))

Cross validation for Naive Bayes:  [0.998 0.999 1.    0.999 0.999 0.999 0.999 0.999 0.999 0.999]


In [15]:
confusion_matrix(Y, y_pred)

array([[284246,     69],
       [   174,    318]], dtype=int64)

In [16]:
X_newFeatures = df_selectedfeatures.loc[:, ~df_selectedfeatures.columns.isin(['Class'])]
Y_newFeatures = df_selectedfeatures['Class']

# Use train_test_split to create the necessary training and test groups
X_train_newFeatures, X_test_newFeatures, y_train_newFeatures, y_test_newFeatures = train_test_split(X_newFeatures, Y_newFeatures, test_size=0.3, random_state=20)
print('With 30% Holdout for Naive Bayes: ' + str(bnb.fit(X_train_newFeatures, y_train_newFeatures).score(X_test_newFeatures, y_test_newFeatures)))
print('Testing on the entire dataset for Naive Bayes: ' + str(bnb.fit(X_newFeatures, Y_newFeatures).score(X_newFeatures, Y_newFeatures)))
confusion_matrix(y_test_newFeatures, bnb.predict(X_test_newFeatures))

With 30% Holdout for Naive Bayes: 0.9984082955888721
Testing on the entire dataset for Naive Bayes: 0.9982725143693799


array([[85307,     0],
       [  136,     0]], dtype=int64)

In [17]:
print("Cross validation for Naive Bayes: ",cross_val_score(bnb, X_newFeatures, Y_newFeatures, cv=10))

Cross validation for Naive Bayes:  [0.998 0.998 0.998 0.998 0.998 0.998 0.998 0.998 0.998 0.998]


In [88]:
from sklearn import ensemble
rfc = ensemble.RandomForestClassifier(random_state = 1,
 criterion = 'entropy',
 n_estimators= 100)
#cross_val_score(rfc, X, Y, cv=10)

In [21]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
print('With 30% Holdout for Random Forest Classifier: ' + str(rfc.fit(X_train_newFeatures, y_train_newFeatures).score(X_test_newFeatures, y_test_newFeatures)))
print(confusion_matrix(y_test_newFeatures, rfc.predict(X_test_newFeatures)))

print('Testing on the entire dataset with new features for Random Forest Classifier: ' + str(rfc.fit(X_newFeatures, Y_newFeatures).score(X_newFeatures, Y_newFeatures)))
print(confusion_matrix(Y_newFeatures, rfc.predict(X_newFeatures)))

print('Testing on the entire dataset for Random Forest Classifier: ' + str(rfc.fit(X, Y).score(X, Y)))
print(confusion_matrix(Y, rfc.predict(X)))

With 30% Holdout for Naive Bayes: 0.9996137776061234
[[85299     8]
 [   25   111]]
Testing on the entire dataset with new features for Random Forest Classifier: 0.9999051989592952
[[284313      2]
 [    25    467]]
Testing on the entire dataset for Random Forest Classifier: 0.9999122212586067
[[284313      2]
 [    23    469]]


In [22]:
print('With 30% Holdout for Random Forest Classifier: ' + str(rfc.fit(X_train, y_train).score(X_test, y_test)))
confusion_matrix(y_test, rfc.predict(X_test))

With 30% Holdout for Random Forest Classifier: 0.9995318516437859


array([[85299,     8],
       [   32,   104]], dtype=int64)

In [51]:
df.count()

Time      284807
V1        284807
V2        284807
V3        284807
V4        284807
V5        284807
V6        284807
V7        284807
V8        284807
V9        284807
V10       284807
V11       284807
V12       284807
V13       284807
V14       284807
V15       284807
V16       284807
V17       284807
V18       284807
V19       284807
V20       284807
V21       284807
V22       284807
V23       284807
V24       284807
V25       284807
V26       284807
V27       284807
V28       284807
Amount    284807
Class     284807
dtype: int64

In [42]:
df.query('Class!=False').count().sum()

15252

In [71]:
df50500 = df.query('Class==False').sample(n=50000)
df_true = df.query('Class==True')
df50500 = pd.concat([df50500,df_true])
df50500.head()

Time         V1        V2        V3        V4        V5        V6  \
46142    42653.0 -10.904882 -5.535735 -2.658936  2.225414 -2.471184  1.433048   
264581  161493.0   2.100766  0.060753 -1.559413  0.018350  0.421145 -0.940195   
125556   77717.0  -1.406656  1.439527  0.787769 -0.692259  0.074352 -0.681233   
181077  124816.0  -0.358059  0.504890  0.704560 -0.458002  0.309560 -0.067563   
181869  125153.0  -1.633725 -0.755173  2.136342  0.932145 -0.042655  0.603678   

              V7        V8        V9  ...       V21       V22       V23  \
46142  -1.202641 -9.299173  0.621437  ... -5.078909  1.162507 -1.076966   
264581  0.415617 -0.404088  0.447964  ... -0.136766 -0.177911  0.204216   
125556  0.372390  0.426224 -0.496895  ... -0.117104 -0.657073 -0.043551   
181077  0.316481  0.056714  0.341158  ... -0.062062 -0.129016  0.099727   
181869 -1.393022  1.021087  1.455374  ...  0.294343  0.797138 -0.315000   

             V24       V25       V26       V27       V28   Amount  Class  
46142   0.888408  0.644787  0.737527  3.063540 -1.602655  1000.56      0  
264581  0.782064  0.103926 -0.115995 -0.045660 -0.053661     1.00      0  
125556 -0.067205 -0.265113 -0.124916 -0.243012  0.130746     4.49      0  
181077  0.525172 -0.695646  0.179572 -0.022548  0.108844    67.16      0  
181869 -0.623844 -0.055489 -0.469453  0.160280 -0.070434    15.00      0  

[5 rows x 31 columns]

In [72]:
df50500.count()

Time      50492
V1        50492
V2        50492
V3        50492
V4        50492
V5        50492
V6        50492
V7        50492
V8        50492
V9        50492
V10       50492
V11       50492
V12       50492
V13       50492
V14       50492
V15       50492
V16       50492
V17       50492
V18       50492
V19       50492
V20       50492
V21       50492
V22       50492
V23       50492
V24       50492
V25       50492
V26       50492
V27       50492
V28       50492
Amount    50492
Class     50492
dtype: int64

In [48]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [89]:
X_sample = df50500.loc[:, ~df50500.columns.isin(['Class'])]
Y_sample = df50500['Class']
rfc_fit = rfc.fit(X_sample, Y_sample)
print(confusion_matrix(Y, rfc_fit.predict(X)))

[[284258     57]
 [     0    492]]


In [106]:
from sklearn.model_selection import KFold
#scores = []
kf = KFold(n_splits = 5, random_state = 42, shuffle = True)

for train_index, test_index in kf.split(X_sample):
    X_Ktrain, X_Ktest, y_Ktrain, y_Ktest = X_sample.iloc[train_index], X_sample.iloc[test_index], Y_sample.iloc[train_index], Y_sample.iloc[test_index]
    rfc_Kfit = rfc.fit(X_Ktrain, y_Ktrain)
    print(confusion_matrix(y_Ktest, rfc_Kfit.predict(X_Ktest)))
    scores.append(rfc_Kfit.score(X_Ktest, y_Ktest))
print(scores)

[[10007     4]
 [   17    71]]
[[9997    1]
 [  21   80]]
[[9997    0]
 [  16   85]]
[[9993    2]
 [  21   82]]
[[9996    3]
 [  12   87]]


In [ ]:
#Logistic regression